stages:
  - build
  - artifact
  - deploy

variables:
  AWS_REGION: us-east-1
  ECS_CLUSTER: Java-Cluster
  ECS_SERVICE: java-service

build:
  stage: build
  image: openjdk:11
  script:
    - echo "Building the Java application"

artifact:
  stage: artifact
  script:
    - echo "Creating artifact"
    - mkdir artifacts
  artifacts:
    paths:
      - artifacts/

deploy:
  stage: deploy
  image: python:3.9
  script:
    - echo "Deploying the Java application to AWS ECS"
    - apt-get update && apt-get install -y unzip
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_REGION
    - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
